# -*- coding: utf-8 -*-
"""Syntax_Surgeon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qd7YkBcFy4DfiDGrFemRnm4AsVcFm1zf
"""

# use a pipeline as a high-level helper
from transformers import pipeline
pipe = pipeline ("text-generation",model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user" ,"content":"who are you?"},
]
pipe(messages)

#Load model directly

from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")

model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")

messages = [
    {"role": "user", "content": "who are you?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=48)

print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio transformers torch black autopep8 reportlab requests

!pip install -q gradio transformers torch black autopep8 reportlab requests

import gradio as gr
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
import torch
import ast
import re
from datetime import datetime
from pathlib import Path
import json
import black
import autopep8
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
import requests
import os

class ChatbotConfig:
    MODEL_NAME = "ibm-granite/granite-3.3-2b-instruct"
    DEFAULT_TEMP = 0.7
    DEFAULT_MAX_TOKENS = 256
    DEFAULT_TOP_P = 0.95

conversation_history = []
model_pipe = None
chat_history = [] # For Gradio display

def load_model():
    global model_pipe
    print("Loading IBM Granite 3.3 2B Instruct model...")
    device = 0 if torch.cuda.is_available() else -1
    device_type = "GPU" if device != -1 else "CPU"
    print(f"Using: {device_type}")

    # Load tokenizer and model separately to ensure proper pipeline creation
    tokenizer = AutoTokenizer.from_pretrained(ChatbotConfig.MODEL_NAME)
    model = AutoModelForCausalLM.from_pretrained(ChatbotConfig.MODEL_NAME)

    model_pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        device=device,
        # Changed torch_dtype to dtype as per deprecation warning
        dtype=torch.float16 if device != -1 else torch.float32,
    )
    print("Model loaded successfully!")
    return model_pipe

def detect_python_code(text):
    code_patterns = [
        r'def\s+\w+\(',
        r'class\s+\w+\(?',
        r'import\s+\w+',
        r'from\s+\w+\s+import',
        r'if\s+.*?:',
        r'for\s+.*?\s+in\s+.*?:',
        r'while\s+.*?:',
        r'try\s*:',
        r'except\s*:',
        r'finally\s*:',
        r'with\s+.*?\s+as\s+.*?:',
        r'lambda\s+.*?:',
    ]
    return any(re.search(pattern, text, re.DOTALL) for pattern in code_patterns)

def check_syntax(code):
    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        return False, f"Syntax Error (line {e.lineno}): {e.msg}"
    except Exception as e:
        return False, f"Error: {str(e)}"

def fix_code_indentation(code):
    lines = code.split("\n")
    fixed_lines = [line.rstrip().replace("\t", "    ") for line in lines]
    return "\n".join(fixed_lines)

def fix_code_brackets(code):
    # This function is a simplified attempt; complex bracket matching is hard with regex alone.
    # black and autopep8 are more robust for this.
    # Basic balancing for common issues, but relies heavily on black/autopep8 for true fix.
    open_paren = code.count('(')
    close_paren = code.count(')')
    if open_paren > close_paren:
        code += ')' * (open_paren - close_paren)
    elif close_paren > open_paren:
        code = '(' * (close_paren - open_paren) + code

    open_square = code.count('[')
    close_square = code.count(']')
    if open_square > close_square:
        code += ']' * (open_square - close_square)
    elif close_square > open_square:
        code = '[' * (close_square - open_square) + code

    open_curly = code.count('{')
    close_curly = code.count('}')
    if open_curly > close_curly:
        code += '}' * (open_curly - close_curly)
    elif close_curly > open_curly:
        code = '{' * (close_curly - open_curly) + code

    return code

def format_code(code):
    try:
        return black.format_str(code, mode=black.FileMode())
    except Exception:
        try:
            return autopep8.fix_code(code)
        except Exception:
            return code

def fix_python_code(code):
    code = fix_code_indentation(code)
    code = fix_code_brackets(code)
    is_valid, error_msg = check_syntax(code)

    if not is_valid:
        return {'success': False, 'fixed_code': code, 'error': error_msg, 'message': f"Could not fully fix code: {error_msg}"}

    code = format_code(code)

    # Re-check syntax after formatting, as formatting can sometimes introduce new issues
    is_valid, error_msg = check_syntax(code)
    if not is_valid:
        return {'success': False, 'fixed_code': code, 'error': error_msg, 'message': f"Code formatted but new syntax error: {error_msg}"}

    return {'success': True, 'fixed_code': code, 'error': None, 'message': "Code fixed and formatted successfully!"}

def generate_response(user_message, temperature, max_tokens, top_p):
    global conversation_history
    conversation_history.append({"role": "user", "content": user_message})

    try:
        # Ensure messages are correctly formatted for the tokenizer
        inputs = model_pipe.tokenizer.apply_chat_template(
            conversation_history,
            add_generation_prompt=True,
            return_dict=True,
            return_tensors="pt",
        ).to(model_pipe.model.device)

        outputs = model_pipe.model.generate(
            **inputs,
            max_new_tokens=int(max_tokens),
            temperature=temperature,
            do_sample=True,
            top_p=top_p
        )

        # Decode the generated tokens
        assistant_message_raw = model_pipe.tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
        assistant_message = assistant_message_raw.strip()

        conversation_history.append({"role": "assistant", "content": assistant_message})
        return assistant_message
    except Exception as e:
        error_response = f"Error: {str(e)}"
        conversation_history.append({"role": "assistant", "content": error_response})
        return error_response

def process_user_input(user_message, temperature, max_tokens, top_p, chat_history_gr):
    global conversation_history, chat_history
    chat_history = chat_history_gr # Sync Gradio chat history

    if not user_message.strip():
        return chat_history

    # Check for python code block pattern ```python\n<code>\n``` or just plain code
    # Improved regex to capture code block or assume whole message is code if it looks like it
    code_match = re.search(r'```python\n(.*?)```', user_message, re.DOTALL)
    if code_match:
        code_snippet = code_match.group(1).strip()
    elif detect_python_code(user_message):
        code_snippet = user_message.strip()
    else:
        code_snippet = None

    if code_snippet:
        fix_result = fix_python_code(code_snippet)

        response_text = f"**Code Fixer Result:**\n"
        response_text += f"*Status*: {fix_result['message']}\n"

        if fix_result['success']:
            response_text += f"```python\n{fix_result['fixed_code']}\n```\n"
            # Generate AI explanation only for successfully fixed code
            ai_response = generate_response(f"I fixed this Python code: \n```python\n{fix_result['fixed_code']}\n```\nBriefly explain what it does and what was fixed.", temperature, max_tokens, top_p)
            chat_history.append((user_message, response_text + "\n\n**AI Explanation:**\n" + ai_response))
        else:
            response_text += f"*Error*: {fix_result['error']}\n"
            response_text += f"**Original Code:**\n```python\n{code_snippet}\n```\n"
            response_text += f"**Attempted Fix:**\n```python\n{fix_result['fixed_code']}\n```\n"
            chat_history.append((user_message, response_text))
    else:
        # Regular chat message
        ai_response = generate_response(user_message, temperature, max_tokens, top_p)
        chat_history.append((user_message, ai_response))

    return chat_history

def clear_chat():
    global conversation_history, chat_history
    conversation_history.clear()
    chat_history.clear()
    return [], ""

def download_txt():
    filename = "chat_history.txt"
    try:
        with open(filename, "w", encoding="utf-8") as f:
            for i, msg in enumerate(conversation_history):
                f.write(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {msg['role'].upper()}:\n")
                f.write(f"{msg['content']}\n\n")
        return f"Downloaded {filename}", filename
    except Exception as e:
        return f"Error: {str(e)}", None

def download_pdf():
    filename = "chat_history.pdf"
    try:
        doc = SimpleDocTemplate(filename, pagesize=letter)
        story = []

        styles = getSampleStyleSheet()
        title_style = styles['h1']
        normal_style = styles['Normal']

        # User message style
        user_style = ParagraphStyle(
            'UserMessage',
            parent=normal_style,
            fontSize=10,
            textColor=colors.blue,
            spaceAfter=8,
            spaceBefore=8,
            borderColor=colors.blue,
            borderWidth=1,
            borderPadding=8,
            leftIndent=20,
            rightIndent=20,
            backColor=colors.lightsteelblue,
        )

        # Assistant message style
        assistant_style = ParagraphStyle(
            'AssistantMessage',
            parent=normal_style,
            fontSize=10,
            textColor=colors.purple,
            spaceAfter=8,
            spaceBefore=8,
            borderColor=colors.purple,
            borderWidth=1,
            borderPadding=8,
            leftIndent=20,
            rightIndent=20,
            backColor=colors.lavender,
        )

        # Header
        story.append(Paragraph("Granite Chatbot Complete Chat History", title_style))
        story.append(Paragraph(f"<b>Exported on:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
        story.append(Paragraph(f"<b>Total Messages:</b> {len(conversation_history)}", normal_style))
        story.append(Spacer(1, 0.3 * inch))

        # Add each message
        for i, msg in enumerate(conversation_history, 1):
            role = msg['role'].upper()
            content_text = msg['content']

            # Clean HTML characters for ReportLab
            clean_text = content_text.replace('<', '&lt;').replace('>', '&gt;')

            story.append(Paragraph(f"<b>Message #{i}</b> <b style=\"color: {user_style.textColor if msg['role']=='user' else assistant_style.textColor}\">({role})</b>", normal_style))
            if msg['role'] == 'user':
                story.append(Paragraph(clean_text, user_style))
            else:
                story.append(Paragraph(clean_text, assistant_style))
            story.append(Spacer(1, 0.2 * inch))

            # Add page break after every 5 messages to keep content readable
            if i % 5 == 0 and i < len(conversation_history):
                story.append(PageBreak())

        # Footer
        story.append(Spacer(1, 0.3 * inch))
        story.append(Paragraph("<i>End of Chat History | Generated by Granite Chatbot</i>", normal_style))

        doc.build(story)
        return f"Downloaded {filename}", filename
    except Exception as e:
        return f"Error: {str(e)}", None

def generate_share_link():
    # As per the task, no external API keys are used. This will return a placeholder.
    if not conversation_history:
        return "No chat history to share."

    summary_text = f"Chat Summary (Messages: {len(conversation_history)}, Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')})\n\n"
    for msg in conversation_history:
        summary_text += f"{msg['role'].upper()}: {msg['content']}\n"

    # In a real scenario, you'd integrate with a service like Pastebin here.
    # For this task, we will provide a mock shareable link text.
    mock_link = f"https://mockshare.com/chat/{hash(frozenset(summary_text.items()))}"

    return f"SHAREABLE LINK: {mock_link}\n\nShare this text or download PDF/TXT for full history.\n\nSummary: {summary_text[:200]}..."

# Load the model once when the script starts
load_model()

with gr.Blocks(title="Granite Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# Granite Chatbot\n### Chat Python Code Fixer (No API Keys)")

    with gr.Row():
        with gr.Column(scale=3):
            chatbot = gr.Chatbot(label="Chat History", height=400, show_copy_button=True, render_markdown=True)
            with gr.Row():
                msg = gr.Textbox(label="Message", placeholder="Type message or paste Python code...", lines=2, scale=4)
                submit_btn = gr.Button("Send", scale=1, size="lg", variant="primary")

            with gr.Row():
                temperature = gr.Slider(label="Temperature", minimum=0.1, maximum=1.0, value=ChatbotConfig.DEFAULT_TEMP, step=0.05)
                max_tokens = gr.Slider(label="Max New Tokens", minimum=50, maximum=1024, value=ChatbotConfig.DEFAULT_MAX_TOKENS, step=50)
                top_p = gr.Slider(label="Top-P", minimum=0.1, maximum=1.0, value=ChatbotConfig.DEFAULT_TOP_P, step=0.05)

            submit_btn.click(
                process_user_input,
                inputs=[msg, temperature, max_tokens, top_p, chatbot],
                outputs=[chatbot],
                api_name="chat"
            )
            msg.submit(
                process_user_input,
                inputs=[msg, temperature, max_tokens, top_p, chatbot],
                outputs=[chatbot]
            )

        with gr.Column(scale=1):
            gr.Markdown("### Controls")
            clear_btn = gr.Button("Clear Chat", variant="stop", size="sm")
            clear_btn.click(clear_chat, outputs=[chatbot, msg])

            gr.Markdown("--- --- ---\n### Download Chat")
            txt_btn = gr.Button("Download TXT", size="sm", variant="secondary")
            pdf_btn = gr.Button("Download PDF", size="sm", variant="secondary")

            status_txt_dl = gr.Textbox(label="TXT Download Status", interactive=False, lines=1)
            txt_file_dl = gr.File(label="Download TXT File", visible=True, file_count="single")

            status_pdf_dl = gr.Textbox(label="PDF Download Status", interactive=False, lines=1)
            pdf_file_dl = gr.File(label="Download PDF File", visible=True, file_count="single")

            txt_btn.click(download_txt, outputs=[status_txt_dl, txt_file_dl])
            pdf_btn.click(download_pdf, outputs=[status_pdf_dl, pdf_file_dl])

            gr.Markdown("--- --- ---\n### Share Link")
            share_btn = gr.Button("Generate Share Link", size="sm", variant="secondary")
            share_output = gr.Textbox(label="Share Link", interactive=False, lines=5)
            share_btn.click(generate_share_link, outputs=[share_output])

    print("\nGRANITE CHATBOT LAUNCHED!\n")
    demo.launch(share=True, show_error=True, show_api=False)